apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: movie-analyst-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-analyst-api
  template:
    metadata:
      labels:
        app: movie-analyst-api
    spec:
      containers:
        - name: movie-analyst-api
          image: juancastaneda20/movie-analyst-api:master4b67dfbcc332da9e3a2a4b4d14e939290005eeab
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: name
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: movie-analyst-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

